# WORDS FOR HANGMAN GAME
words = [
    "abandon", "ability", "absence", "abuse", "academic", "accept", "accuse", "achieve",
    "acquire", "advice", "allege", "alumni", "amplify", "anxiety", "arrival", "assist",
    "athlete", "balance", "bitter", "breeze", "brought", "button", "calendar", "capture",
    "carpet", "chicken", "choose", "chronic", "cluster", "courage", "creator", "delight",
    "disease", "document", "doubt", "dynamic", "elegant", "exceed", "fallout", "flavor",
    "forget", "gather", "glisten", "harmony", "honest", "impact", "income", "inquire",
    "jacket", "journey", "juggle", "keenly", "kitchen", "lethal", "lively", "lumber",
    "mansion", "master", "merely", "mimic", "moment", "mortal", "noble", "nomadic",
    "offend", "orange", "outfit", "packet", "planet", "pocket", "profit", "quaint",
    "quench", "quiet", "rattle", "reason", "remedy", "rival", "safety", "scout", "scraps",
    "serene", "shame", "shovel", "signal", "smile", "sneak", "sword", "tackle", "tender",
    "thrive", "ticket", "vivid", "waste", "weather", "waste", "winter", "wonder", "wrist",
    "yonder", "zebra", "zoom", "zephyr", "apple", "banana", "kiwi", "peach", "cherry",
    "apricot", "grape", "lemon", "mango", "orange", "pear", "plum", "pineapple", "melon",
    "watermelon", "apricot", "blackberry", "strawberry", "blueberry", "cantaloupe", "abandonment",
    "absolute", "absurd", "academy", "acres", "actress", "advance", "africa", "alchemist",
    "allele", "alligator", "alphabet", "altruism", "amazing", "anagram", "anthem", "archipelago",
    "assassin", "astronaut", "athletic", "bargain", "belly", "berserk", "betrayal", "bitterly",
    "bizarre", "blizzard", "bother", "breathe", "bricks", "buffalo", "burden", "cactus",
    "canine", "catfish", "charming", "climate", "climate", "clumsy", "coastal", "confess",
    "contest", "create", "curious", "danger", "decent", "deprived", "direct", "disease",
    "disgust", "dumbbell", "eco-friendly", "elaborate", "empower", "enthusiasm", "excited",
    "express", "feedback", "feverish", "flinch", "galaxy", "generous", "genuine", "giraffe",
    "glimmer", "goodness", "hurricane", "historian", "hopeless", "imagine", "inspire", "jellyfish",
    "juniper", "juggler", "jumpy", "karma", "kitten", "lilac", "lovely", "majesty", "marvel",
    "memento", "mercy", "mimic", "mystery", "narrate", "notion", "outdoor", "paintbrush", "panther",
    "parent", "peculiar", "pirate", "plague", "portray", "potion", "quest", "quintessential",
    "radical", "rebirth", "resilient", "reborn", "relax", "relent", "scout", "sensational", "silence",
    "surprise", "synchronicity", "transcend", "urgent", "valley", "vicious", "voyage", "weaver",
    "whisper", "yoga", "zodiac", "zephyr", "abundance", "accordion", "astronomy", "battalion",
    "bilingual", "biography", "champion", "chocolate", "circuit", "conscious", "constant",
    "creativity", "destination", "different", "elevation", "enlighten", "enchanted", "eternal",
    "familiar", "fascinate", "freedom", "glorious", "glow", "grove", "horizon", "impression",
    "jovial", "keen", "lively", "meaning", "numerous", "opulent", "outfit", "perplexing", "refuge",
    "regret", "righteous", "sensitive", "splendid", "teleport", "tension", "universal", "utopia",
    "vintage", "vividly", "vulnerable", "wonderful", "achievement", "ambition", "account",
    "affection", "beautiful", "breathe", "bravery", "brilliant", "crystal", "daydream",
    "delightful", "endurance", "fascinating", "generosity", "harmony", "hilarious",
    "impressive", "inspire", "jovial", "kindness", "laughter", "lovely", "magnificent",
    "mysterious", "optimistic", "reliability", "spectacular", "tremendous", "unbelievable",
    "wonderful", "zealous", "apocalyptic", "desirable", "extraordinary", "funny", "genuine",
    "innovative", "melodic", "noble", "romantic", "symbolic", "thriving", "unrivaled", "unexpected"
]
